---
- name: Configure Quay
  hosts: all
  become: yes
  vars_prompt:
    - name: username
      prompt: "Enter the rhsm username"
      private: no
    - name: password
      prompt: "Enter the rhsm password"
      private: yes
    - name: registryusername
      prompt: "Enter the registry.redhat.io username"
      private: no
    - name: registrypassword
      prompt: "Enter the registry.redhat.io  password"
      private: yes
  tasks:
    - name: Stopping the quay container
      ansible.builtin.shell:
        cmd:
          podman stop quay
    - name: Creating quay container configuration
      ansible.builtin.shell:
        cmd: |
          mkdir $QUAY/config
          cp quay-config.tar.gz $QUAY/config
          cd $QUAY/config
          tar -xvf quay-config.tar.gz
          mkdir $QUAY/storage
          setfacl -m u:1001:-wx $QUAY/storage
    - name: Starting the actual QUAY container
      ansible.builtin.shell:
        cmd: |
          podman run -d --rm -p 80:8080 -p 443:8443 --name=quay -v $QUAY/config:/conf/stack:Z -v $QUAY/storage:/datastorage:Z registry.redhat.io/quay/quay-rhel8:v3.10.5
    - name: Print message login and configure quay
      ansible.builtin.debug:
        msg: "QUAY is installed and configured, you can login to quay by browsing the http://{{ ansible_fqdn }}"
